services:
  productsdb:
     container_name: productsdb
     ports:
       - "3309:3306"
     environment:
       MYSQL_DATABASE: productsdb
     extends:
       file: common-config.yml
       service: microservice-db-config
  
  customerdb:
     container_name: customerdb
     ports:
        - "3307:3306"
     environment:
        MYSQL_DATABASE: customerdb
     extends:
        file: common-config.yml
        service: microservice-db-config

  sales_orderdb:
     container_name: sales_orderdb
     ports:
       - "3308:3306"
     environment:
       MYSQL_DATABASE: sales_orderdb
     extends:
       file: common-config.yml
       service: microservice-db-config
  
  configserver:
     image: yvenkatesh954/configserver:s1
     container_name: configserver-ms
     ports:
        - "8093:8093"
     healthcheck:
        test: "curl --fail --silent localhost:8093/actuator/health/readiness | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
     extends:
      file: common-config.yml
      service: microservice-base-config
      
  eurekaserver:
     image: yvenkatesh954/eurekaserver:s1
     container_name: eurekaserver-ms
     ports:
        - "8094:8094"
     healthcheck:
        test: "curl --fail --silent localhost:8094/actuator/health/readiness | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
     extends:
      file: common-config.yml
      service: microservice-configserver-config
     environment:
        SPRING_APPLICATION_NAME: "eurekaserver"
  
  products:
     image: yvenkatesh954/products:s1
     container_name: products-ms
     ports:
        - "8090:8090"
     healthcheck:
        test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
     depends_on:
        productsdb:
           condition: service_healthy
     environment:
        SPRING_APPLICATION_NAME: "products"
        SPRING_DATASOURCE_URL: "jdbc:mysql://productsdb:3306/productsdb"
     extends:
        file: common-config.yml
        service: microservice-eureka-config
        
  customer:
    image: yvenkatesh954/customer:s1
    container_name: customer-ms
    ports:
       - "8091:8091" 
    healthcheck:
        test: "curl --fail --silent localhost:8091/actuator/health/readiness | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s   
    depends_on:
       customerdb:
          condition: service_healthy
    environment:
       SPRING_APPLICATION_NAME: "customer"
       SPRING_DATASOURCE_URL: "jdbc:mysql://customerdb:3306/customerdb"
    extends:
       file: common-config.yml
       service: microservice-eureka-config
        
  sales-order:
     image: yvenkatesh954/sales-order:s1
     container_name: sales-order-ms
     ports:
        - "8092:8092"
     healthcheck:
        test: "curl --fail --silent localhost:8092/actuator/health/readiness | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
     depends_on:
        sales_orderdb:
          condition: service_healthy
     environment:
        SPRING_APPLICATION_NAME: "sales-order"
        SPRING_DATASOURCE_URL: "jdbc:mysql://sales_orderdb:3306/sales_orderdb"
     extends:
      file: common-config.yml
      service: microservice-eureka-config
  gatewayserver:
     image: yvenkatesh954/gatewayserver:s1
     container_name: gatewayserver-ms
     ports:
        - "8095:8095"
     depends_on:
        products:
          condition: service_healthy
        customer:
          condition: service_healthy
        sales-order:
          condition: service_healthy     
     environment:
        SPRING_APPLICATION_NAME: "gatewayserver"
     extends:
      file: common-config.yml
      service: microservice-eureka-config    
networks:
  ecart:
    driver: bridge
        